[package]
name = "sp1-tee-prover"
version.workspace = true
edition.workspace = true

[dependencies]
tdx = { git = "https://github.com/automata-network/tdx-attestation-sdk.git" }

alloy.workspace = true
anyhow.workspace = true
env_logger.workspace = true
hex.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
log.workspace = true
rand.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json.workspace = true
sp1-sdk.workspace = true
tokio.workspace = true
lazy_static.workspace = true
uuid.workspace = true
web3.workspace = true
tiny-keccak = "2.0.2"
clap = { version = "4.5.23", features = ["derive"] }
